version: "3.8"

services:
  backend:
    build: ./backend
    image: mcp-audit-backend:dev
    container_name: mcp-audit-backend
    environment:
      - LLM_MOCK=${LLM_MOCK:-1}
      - MCP_GDRIVE_URL=http://mcp-gdrive:8787
      - MCP_LLM_URL=http://mcp-llm:8788
    ports:
      - "8010:8010"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010"]
    working_dir: /app
    volumes:
      - ./backend:/app

  mcp-gdrive:
    image: ghcr.io/isaacphi/mcp-gdrive:latest
    container_name: mcp-gdrive
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    ports:
      - "8787:8787"

  mcp-llm:
    image: ghcr.io/modelcontextprotocol/llm-server:latest
    container_name: mcp-llm
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "8788:8788"
